# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a96680cb0d1803f72226f70a560f24b040a0f5a29ba77a85ec8a58394e12b1e081129c543aabacbeb26ae301ac0c0b40a4d3c5522a4b3d61c7c08edab188f97

test:
  secret_key_base: 6864b07aa839980cc7faa43eba32d05bb0f482608f77dd5e8d294eaf4e49485835955836421b6d067ed5a521acc2974ffbad536bd88b2e6deb4fb66213ff2041

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
